In [1]:
import numpy as np
array=np.arange(20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Numpy

In [3]:
array=np.arange(18).reshape(3,6)

In [4]:
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [6]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.29240893e-321],
       [1.97345609e-312, 0.00000000e+000, 0.00000000e+000]])

In [9]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

# Functions in Numpy

In [14]:
import numpy as np
a=np.arange(10)
a
np.empty_like(a)

array([1534599211,  706764139, 1851486240,  542978349, 1534074923,
       1025531246, 1801156896, 1409944157, 1663067496, 1717986671])

In [15]:
import numpy as np
a=np.arange(10)
a
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
import numpy as np
a=np.arange(10)
a
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
import numpy as np
a=np.arange(10)
a
np.full_like(a,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [18]:
import numpy as np
a=np.arange(10)
a
np.asarray(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
import numpy as np
a=np.arange(10)
a
np.geomspace(2,10,5)

array([ 2.        ,  2.99069756,  4.47213595,  6.68740305, 10.        ])

In [20]:
np.diag(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [24]:
np.random.random((2,3))


array([[0.44258598, 0.21129856, 0.04143137],
       [0.67603761, 0.27223774, 0.63527083]])

# Numpy array indexing

In [27]:
import numpy as np
a=np.array([1,2,3,4])
a[2]

3

In [31]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(a[1,0,2])

9


In [32]:
import numpy as np
a=np.array([[1,2,3,4],[6,7,8,5]])
print(a[1,-1])

5


# Numpy array slicing

In [33]:
a=np.array([1,2,3,4,5,6])
print(a[1:5])

[2 3 4 5]


In [34]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:4])


[7 8 9]


In [35]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,2])

[3 8]


In [36]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [37]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
x=a.reshape(-1)
print(x)

[1 2 3 4 5 6]


# Iterating 2D arrays

In [40]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
for x in a:
    print(x)


[1 2 3]
[4 5 6]


In [42]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
for x in a:
    for y in x:
     print(y)

1
2
3
4
5
6


In [44]:
import numpy as np
a=np.array([1,2,3])
for idx,x in np.ndenumerate(a):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [45]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate((a,b))
print(x)

[1 2 3 4 5 6]


In [46]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.stack((a,b),axis=1)
print(x)

[[1 4]
 [2 5]
 [3 6]]


In [53]:
import numpy as np
a=np.array([9,0,5,8])
print(np.sort(a))

[0 5 8 9]


In [56]:
import numpy as np
a=np.array([[0,19,11],[2,6,1]])
print(np.sort(a))

[[ 0 11 19]
 [ 1  2  6]]


In [1]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [2]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


In [3]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))

Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


In [4]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


In [5]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [6]:
import numpy as np
x=np.array([1,7,13,105])
print("original array:")
print(x)
print("size of the memory occupied by the said array:")
print("%d bytes"%(x.size*x.itemsize))

original array:
[  1   7  13 105]
size of the memory occupied by the said array:
16 bytes


In [7]:
import numpy as np
array_2D=np.identity(3)
print("3*3 matrix:")
print(array_2D)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
import numpy as np
m=np.arange(10,22).reshape((3,4))
print("original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)

original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and columns of the said matrix:
(3, 4)


In [9]:
import numpy as np
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [10]:
import numpy as np
nums=np.array([[5.54,3.38,7.99],
              [3.54,4.38,6.99],
              [1.54,2.39,9.29]])
print("original array:")
print(nums)
print("/nsort array by row in ascending order:")
print(np.sort(nums))
print("/nsort array by column in ascending order:")
print(np.sort(nums,axis=0))

original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
/nsort array by row in ascending order:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
/nsort array by column in ascending order:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [14]:
import numpy as np
nums=np.array([[[1,2,3,4],
              [0,1,3,4],
              [90,91,93,94],
              [5,0,3,2]]])
print("original array:")
print(nums)
print("/nswap rows and columns of the array in reverse order")
new_nums=print(nums[::-1,::-1])
print(new_nums)

original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]
/nswap rows and columns of the array in reverse order
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


In [15]:
import numpy as np
nums1=np.array([[2,5,2],
               [1,5,5]])
nums2=np.array([[5,3,4],
                [3,2,5]])
print("array1:")
print(nums1)
print("array2:")
print(nums2)
print("/n multiply said arrays of same size element-by-element:")
print(np.multiply(nums1,nums2))

array1:
[[2 5 2]
 [1 5 5]]
array2:
[[5 3 4]
 [3 2 5]]
/n multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]
